description: The ultimate undo history visualizer for Vim
dependencies:
  - vim.pathogen
prepare:
  - kind: git clone
    remote: "http://github.com/mbbill/undotree"
install:
  - kind: copy tree
    folder: "$TEMPORARY_DIR/undotree"
    to: "$HOME/.vim/bundle/undotree"
  - kind: copy
    file: config.vim
    to: "$HOME/.vim/config/undotree.vim"
