description: The ultimate undo history visualizer for Vim
dependencies:
  - vim.pathogen
prepare:
  - action: git clone
    repository: "http://github.com/mbbill/undotree"
install:
  - action: copy tree
    dir: "$TEMPORARY_DIR/undotree"
    to: "$HOME/.vim/bundle/undotree"
  - action: copy
    file: config.vim
    to: "$HOME/.vim/config/undotree.vim"
