description: Installs some fancy utilities that make Shell-usage experience
  better and quicker.
dependencies:
  - basic
superuser: true
prepare:
  - action: shell all
    commands:
      - "$PACKAGE_DIR/bat.sh"
      - "$PACKAGE_DIR/exa.sh"
      - "$PACKAGE_DIR/fd.sh"
      - "$PACKAGE_DIR/hexyl.sh"
install:
  - action: shell all
    commands:
      - "sudo dpkg --install $TEMPORARY_DIR/fd.deb"
      - "sudo dpkg --install $TEMPORARY_DIR/bat.deb"
      - "sudo dpkg --install $TEMPORARY_DIR/hexyl.deb"
  - action: make dirs
    dirs:
      - "$HOME/bin"
  - action: copy
    file: "$TEMPORARY_DIR/exa"
    to: "$HOME/bin/exa"
  - action: copy
    file: exa_aliases.sh
    to: "$HOME/.bash.d/exa.sh"
