description: Vim support for (La)TeX code editing
dependencies:
  - vim.pathogen
prepare:
  - action: git clone
    repository: "http://github.com/lervag/vimtex"
install:
  - action: copy tree
    folder: "$TEMPORARY_DIR/vimtex"
    to: "$HOME/.vim/bundle/vimtex"
