description: CMake is a cross-platform open-source build system designed to
  generate build tooling invocations (such as for 'make' and 'ninja') based on
  build instructions written in a common DSL. It also allows for extensive
  modularisation and automatic finding of environment dependencies, etc.
dependencies:
  - internal.virtualenv
prepare:
  - kind: shell multiple
    commands:
      - "bash -c 'source $SESSION_DIR/dotfiles-venv/bin/activate; pip install bs4 lxml'"
      - "bash -c 'source $SESSION_DIR/dotfiles-venv/bin/activate; $PACKAGE_DIR/select-latest-version.py > $TEMPORARY_DIR/url.txt'"
      - "wget \"$(cat $TEMPORARY_DIR/url.txt)\" -O cmake.tar.gz"
      - "tar -xf cmake.tar.gz"
      - "mv cmake-* cmake"
install:
  - kind: make folders
    folders:
      - "$HOME/bin"
      - "$HOME/opt"
  - kind: copy tree
    folder: "$TEMPORARY_DIR/cmake"
    to: "$HOME/opt/cmake"
  - kind: shell
    command: "cd $HOME/bin; ln -s ../opt/cmake/bin/* ."
