description: File system directory tree plugin for Vim
dependencies:
  - vim.pathogen
prepare:
  - kind: git clone
    remote: "http://github.com/scrooloose/nerdtree"
install:
  - kind: copy tree
    folder: "$TEMPORARY_DIR/nerdtree"
    to: "$HOME/.vim/bundle/nerdtree"
  - kind: copy
    file: config.vim
    to: "$HOME/.vim/config/nerdtree.vim"
