description: File system directory tree plugin for Vim
dependencies:
  - vim.pathogen
prepare:
  - action: git clone
    repository: "http://github.com/scrooloose/nerdtree"
install:
  - action: copy tree
    folder: "$TEMPORARY_DIR/nerdtree"
    to: "$HOME/.vim/bundle/nerdtree"
  - action: copy
    file: config.vim
    to: "$HOME/.vim/config/nerdtree.vim"
