description: Vim plugin for invoking 'clang-format'
dependencies:
  - vim.pathogen
prepare:
  - kind: git clone
    remote: "http://github.com/rhysd/vim-clang-format"
install:
  - kind: copy tree
    folder: "$TEMPORARY_DIR/vim-clang-format"
    to: "$HOME/.vim/bundle/vim-clang-format"
  - kind: copy
    file: config.vim
    to: "$HOME/.vim/config/vim-clang-format.vim"
