description: "pathogen.vim: Manage Vim plugins with ease!"
prepare:
  - action: git clone
    repository: "http://github.com/tpope/vim-pathogen"
install:
  - action: make dirs
    dirs:
      - "$HOME/.vim/autoload"
      - "$HOME/.vim/bundle"
      - "$HOME/.vim/config"
  - action: copy
    file: "$TEMPORARY_DIR/vim-pathogen/autoload/pathogen.vim"
    to: "$HOME/.vim/autoload/pathogen.vim"
  - action: copy
    file: config.vim
    to: "$HOME/.vim/config/pathogen.vim"
