description: Basic user environment files. (This package is initially tailored
  for use on a default Ubuntu 16.04 or 18.04 user account.)
prepare:
  - action: prompt user
    description: The name with which your Git commits will be authored.
    short name: git-user.name
    variable: GIT_USERNAME
  - action: prompt user
    description: The e-mail address with which your Git commits will be authored.
    short name: git-user.email
    variable: GIT_USEREMAIL
install:
  - action: copy
    files:
      - bashrc
      - bash_aliases
      - gitconfig
      - profile
    to: $HOME
    prefix: '.'
  - action: make dirs
    dirs:
      - "$HOME/.ssh"
  - action: copy
    file: ssh/unlock-all
    to: "$HOME/.ssh/unlock-all"
  - action: replace user input
    file: $HOME/.gitconfig
