description: Installs Vim, a pluginable command-line text editor
superuser: true
prepare:
  - action: git clone
    repository: "http://github.com/tomasr/molokai.git"
install:
  - action: shell
    command: "sudo apt-get install -y vim"
  - action: make dirs
    dirs:
      - "$HOME/.vim"
      - "$HOME/.vim/colors"
  - action: extract multiple
    files:
      - .vimrc
      - .vim/init.vim
    root: HOME
  - action: copy
    file: "$TEMPORARY_DIR/molokai/colors/molokai.vim"
    to: "$HOME/.vim/colors/molokai.vim"
