description: Installs Vim, a pluginable command-line text editor
# superuser: true
prepare:
  - action: git clone
    repository: "http://github.com/tomasr/molokai.git"
install:
#  - action: shell
#    command: "sudo apt-get install -y vim"
  - action: make dirs
    dirs:
      - "$HOME/.vim"
      - "$HOME/.vim/colors"
  - action: copy
    file: vimrc
    to: "$HOME/.vimrc"
  - action: copy
    file: init.vim
    to: "$HOME/.vim/init.vim"
  - action: copy
    file: "$TEMPORARY_DIR/molokai/colors/molokai.vim"
    to: "$HOME/.vim/colors/molokai.vim"
