description: Installs tools that format diffs to be better-looking
dependencies:
  - basic
superuser: true
prepare:
  - action: shell all
    commands:
      - 'wget http://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy'
      - chmod +x diff-so-fancy
install:
  - action: make folders
    folders:
      - "$HOME/bin"
  - action: shell
    command: "sudo apt-get install -y --no-install-recommends colordiff"
  - action: copy
    file: "$TEMPORARY_DIR/diff-so-fancy"
    to: "$HOME/bin/diff-so-fancy"
  - action: shell
    command: "git config --global core.pager \"diff-so-fancy | less --tabs=4 -RFX\""
  - action: copy
    file: colourdiff.sh
    to: "$HOME/.bash.d/colourdiff.sh"
