description: Vim status line
dependencies:
  - vim.pathogen
prepare:
  - action: git clone
    repository: "http://github.com/vim-airline/vim-airline"
install:
  - action: copy tree
    dir: "$TEMPORARY_DIR/vim-airline"
    to: "$HOME/.vim/bundle/vim-airline"
  - action: copy
    file: config.vim
    to: "$HOME/.vim/config/vim-airline.vim"
