description: Installs some common and most wanted developer environment tools.
superuser: true
install:
  - kind: shell
    command: "sudo apt-get install -y --no-install-recommends byobu gitk htop mc meld tree"
