description: Change Bash prompt to show Git statuses in a working directory
dependencies:
  - basic
prepare:
  - action: git clone
    repository: "http://github.com/magicmonty/bash-git-prompt"
install:
  - action: copy tree
    folder: "$TEMPORARY_DIR/bash-git-prompt"
    to: "$HOME/.bash.d/git-prompt"
  - action: copy
    file: git-prompt.sh
    to: "$HOME/.bash.d/git-prompt.sh"
