description: Install the TeXLive (La)TeX typesetting environment's latest
  version from the internet.
dependencies:
  - bash
prepare:
  - kind: shell multiple
    commands:
      - "wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz"
      - "tar xvfz install-tl-unx.tar.gz"
      - "rm install-tl-unx.tar.gz"
      - "mv install-tl-* install-tl"
  - kind: shell
    command: "cp $PACKAGE_DIR/texlive.profile $TEMPORARY_DIR/texlive.profile"
install:
  - kind: substitute environment variables
    file: $TEMPORARY_DIR/texlive.profile
  - kind: make folders
    folders:
      - $HOME/opt
  - kind: shell
    command: "$TEMPORARY_DIR/install-tl/install-tl --profile=$TEMPORARY_DIR/texlive.profile"
  - kind: copy
    file: texlive.sh
    to: "$HOME/.bash.d/tex-live.sh"
