description: Download and install the latest version of Python virtualenv.
depend_on_parent: false
superuser: true
prepare:
  - kind: shell multiple
    commands:
      - "$PACKAGE_DIR/get-release.sh"
      - "tar -xf virtualenv.tar.gz"
      - "mv pypa-virtualenv-* virtualenv"
install:
  - kind: shell
    command: "sudo apt-get install -y --no-install-recommends python3-distutils"
  - kind: make folders
    folders:
      - "$HOME/opt"
  - kind: shell multiple
    commands:
      - "mv $TEMPORARY_DIR/virtualenv $HOME/opt/virtualenv"
      - "bash -c 'cd $HOME/opt/virtualenv; ln -s $(find . -name virtualenv.py -type f) virtualenv_s.py'"
