description: Vim syntax checking extension
dependencies:
  - vim.pathogen
prepare:
  - action: git clone
    repository: "http://github.com/scrooloose/syntastic"
install:
  - action: copy tree
    folder: "$TEMPORARY_DIR/syntastic"
    to: "$HOME/.vim/bundle/syntastic"
  - action: copy
    file: config.vim
    to: "$HOME/.vim/config/syntastic.vim"
